int _putchar(char c);
int _isupper(int c);
int -isdigit(int c);
int mul(in a, int b);
void print_numders(void);
void print_most_numbers(void);
void print_numbers(void);
void print_line(int n);
void print_diogonal(int n);
void print_square(int size);
void print_triangle(int size);
void print_number(int n);
